---
title: "Visualization 3"
description: |
  Change in self-regulation scores from 2013 to 2018
author:
  - name: Joanna Wright
    url: https://github.com/jhwrigh23
date: 03-09-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}

library(tidyverse)
library(rio)
library(here)
library(janitor)
library(maps)
library(mapdata)
library(ggtext)

```


```{r loading-the-data}

d <- import(here("data", "ka_2018-19_lookback_report.xlsx")) %>%
  clean_names()

counties <- map_data("county")
or_county <- subset(counties, region == "oregon")

```


```{r cleaning-the-data}

d_tidy <- d %>%
  rename(county = oregon_kindergarten_assessment,
         district_id = x2,
         district = x3,
         inst_id = x4,
         inst_name = x5,
         inst_type = x6,
         stu_grp_type = x7,
         stu_grp = x8,
         avg_self_reg = x9) %>%
  select(c(1:9))

d_tidy <- d_tidy %>%
  filter(avg_self_reg != "*")

# need to double check online what the * means and make sure it's ok to remove. it removed a lot of rows!! 

d_tidy = d_tidy[-1,]

```
